FILE_NAME = "th143.exe"
DISPLAY_NAME = "Danmaku Amanojaku ~ Impossible Spell Card"
SHORT_NAME = "Touhou 14.3"
CLIENT_DESCRIPTION = "AP Client for " + DISPLAY_NAME + "."

APPDATA_PATH = "\\ShanghaiAlice\\th143\\"
AP_SAVE_DATA_FILE_NAME = "th143ap_"
JSON_EXTENSION = ".json"
JSON_SLOT_NAME = "slot_name"
JSON_SLOT_ITEMS = "item"
JSON_SLOT_CLEARS = "clear"
JSON_SLOT_PLAYTIME = "time"
JSON_SLOT_DEATHS = "miss"
CLIENT_DATA_PATH = "data\\th143"
CLIENT_DEBUG_ALERTS = "debug_alerts"

MSG_SERVER_NOT_CONNECTED = "The client hasn't connected to the server yet!"
MSG_GAME_NOT_RUNNING = "The game isn't running!"
MSG_DEATH_LINK_NOT_ENABLED = "Death Link is not enabled for this slot."
MSG_CHANGE_YAML_LOCATIONS = "(Change your .yaml settings to add more locations)"