from typing import Dict, NamedTuple, Optional
from .Variables import *

from BaseClasses import Item, ItemClassification

class TItem(Item):
	game: str = DISPLAY_NAME

class TItemData(NamedTuple):
	category: str
	code: Optional[int] = None
	classification: ItemClassification = ItemClassification.filler
	max_quantity: int = 1
	weight: int = 1

def get_items_by_category(category: str) -> Dict[str, TItemData]:
	item_dict: Dict[str, TItemData] = {}
	for name, data in item_table.items():
		if data.category == category:
			item_dict.setdefault(name, data)

	return item_dict

item_table: Dict[str, TItemData] = {
	# Items
	"+1 Life":				TItemData("Items", STARTING_ID + 0, ItemClassification.progression, 8),
	"+1 Bomb":				TItemData("Items", STARTING_ID + 1, ItemClassification.progression, 8),
	"Lower Difficulty":		TItemData("Items", STARTING_ID + 2, ItemClassification.progression, 3),
	"Time Gain":			TItemData("[Time] Items", STARTING_ID + 3, ItemClassification.progression),
	"+25 Power Point":		TItemData("Power Point", STARTING_ID + 4, ItemClassification.useful, 5),
	"+1000 Time Point":		TItemData("Time Point", STARTING_ID + 5, ItemClassification.useful, 10),

	# Characters
	"Illusionary Barrier Team":		TItemData("Characters", STARTING_ID + 100, ItemClassification.progression),
	"Aria of Forbidden Magic Team":	TItemData("Characters", STARTING_ID + 101, ItemClassification.progression),
	"Visionary Scarlet Devil Team":	TItemData("Characters", STARTING_ID + 102, ItemClassification.progression),
	"Netherworld Dwellers Team":	TItemData("Characters", STARTING_ID + 103, ItemClassification.progression),

	# Stages
	"Next Stage":					TItemData("[Progressive][Global] Stages", STARTING_ID + 200, ItemClassification.progression, 8),
	"[Illusion Team] Next Stage":	TItemData("[Progressive][Character] Stages", STARTING_ID + 201, ItemClassification.progression, 8),
	"[Magic Team] Next Stage":		TItemData("[Progressive][Character] Stages", STARTING_ID + 202, ItemClassification.progression, 8),
	"[Devil Team] Next Stage":		TItemData("[Progressive][Character] Stages", STARTING_ID + 203, ItemClassification.progression, 8),
	"[Nether Team] Next Stage":		TItemData("[Progressive][Character] Stages", STARTING_ID + 204, ItemClassification.progression, 8),
	"Extra Stage":					TItemData("[Global] Extra Stage", STARTING_ID + 205, ItemClassification.progression),
	"[Illusion Team] Extra Stage":	TItemData("[Character] Extra Stage", STARTING_ID + 206, ItemClassification.progression),
	"[Magic Team] Extra Stage":		TItemData("[Character] Extra Stage", STARTING_ID + 207, ItemClassification.progression),
	"[Devil Team] Extra Stage":		TItemData("[Character] Extra Stage", STARTING_ID + 208, ItemClassification.progression),
	"[Nether Team] Extra Stage":	TItemData("[Character] Extra Stage", STARTING_ID + 209, ItemClassification.progression),
	"Stage 2":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 210, ItemClassification.progression),
	"Stage 3":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 211, ItemClassification.progression),
	"Stage 4A":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 212, ItemClassification.progression),
	"Stage 4B":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 213, ItemClassification.progression),
	"Stage 5":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 214, ItemClassification.progression),
	"Stage 6A":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 215, ItemClassification.progression),
	"Stage 6B":						TItemData("[Not Progressive][Global] Stages", STARTING_ID + 216, ItemClassification.progression),
	"[Illusion Team] Stage 2":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 217, ItemClassification.progression),
	"[Illusion Team] Stage 3":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 218, ItemClassification.progression),
	"[Illusion Team] Stage 4A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 219, ItemClassification.progression),
	"[Illusion Team] Stage 4B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 220, ItemClassification.progression),
	"[Illusion Team] Stage 5":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 221, ItemClassification.progression),
	"[Illusion Team] Stage 6A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 222, ItemClassification.progression),
	"[Illusion Team] Stage 6B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 223, ItemClassification.progression),
	"[Magic Team] Stage 2":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 224, ItemClassification.progression),
	"[Magic Team] Stage 3":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 225, ItemClassification.progression),
	"[Magic Team] Stage 4A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 226, ItemClassification.progression),
	"[Magic Team] Stage 4B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 227, ItemClassification.progression),
	"[Magic Team] Stage 5":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 228, ItemClassification.progression),
	"[Magic Team] Stage 6A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 229, ItemClassification.progression),
	"[Magic Team] Stage 6B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 230, ItemClassification.progression),
	"[Devil Team] Stage 2":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 231, ItemClassification.progression),
	"[Devil Team] Stage 3":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 232, ItemClassification.progression),
	"[Devil Team] Stage 4A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 233, ItemClassification.progression),
	"[Devil Team] Stage 4B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 234, ItemClassification.progression),
	"[Devil Team] Stage 5":			TItemData("[Not Progressive][Character] Stages", STARTING_ID + 235, ItemClassification.progression),
	"[Devil Team] Stage 6A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 236, ItemClassification.progression),
	"[Devil Team] Stage 6B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 237, ItemClassification.progression),
	"[Nether Team] Stage 2":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 238, ItemClassification.progression),
	"[Nether Team] Stage 3":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 239, ItemClassification.progression),
	"[Nether Team] Stage 4A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 240, ItemClassification.progression),
	"[Nether Team] Stage 4B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 241, ItemClassification.progression),
	"[Nether Team] Stage 5":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 242, ItemClassification.progression),
	"[Nether Team] Stage 6A":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 243, ItemClassification.progression),
	"[Nether Team] Stage 6B":		TItemData("[Not Progressive][Character] Stages", STARTING_ID + 244, ItemClassification.progression),
	"[Reimu] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 245, ItemClassification.progression, 7),
	"[Yukari] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 246, ItemClassification.progression, 7),
	"[Marisa] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 247, ItemClassification.progression, 7),
	"[Alice] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 248, ItemClassification.progression, 7),
	"[Sakuya] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 249, ItemClassification.progression, 7),
	"[Remilia] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 250, ItemClassification.progression, 7),
	"[Youmu] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 251, ItemClassification.progression, 7),
	"[Yuyuko] Next Stage":			TItemData("[Progressive][Solo Character] Stages", STARTING_ID + 252, ItemClassification.progression, 7),
	"[Reimu] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 253, ItemClassification.progression),
	"[Reimu] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 254, ItemClassification.progression),
	"[Reimu] Stage 4A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 255, ItemClassification.progression),
	"[Reimu] Stage 4B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 256, ItemClassification.progression),
	"[Reimu] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 257, ItemClassification.progression),
	"[Reimu] Stage 6A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 258, ItemClassification.progression),
	"[Reimu] Stage 6B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 259, ItemClassification.progression),
	"[Yukari] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 260, ItemClassification.progression),
	"[Yukari] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 261, ItemClassification.progression),
	"[Yukari] Stage 4A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 262, ItemClassification.progression),
	"[Yukari] Stage 4B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 263, ItemClassification.progression),
	"[Yukari] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 264, ItemClassification.progression),
	"[Yukari] Stage 6A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 265, ItemClassification.progression),
	"[Yukari] Stage 6B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 266, ItemClassification.progression),
	"[Marisa] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 267, ItemClassification.progression),
	"[Marisa] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 268, ItemClassification.progression),
	"[Marisa] Stage 4A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 269, ItemClassification.progression),
	"[Marisa] Stage 4B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 270, ItemClassification.progression),
	"[Marisa] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 271, ItemClassification.progression),
	"[Marisa] Stage 6A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 272, ItemClassification.progression),
	"[Marisa] Stage 6B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 273, ItemClassification.progression),
	"[Alice] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 274, ItemClassification.progression),
	"[Alice] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 275, ItemClassification.progression),
	"[Alice] Stage 4A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 276, ItemClassification.progression),
	"[Alice] Stage 4B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 277, ItemClassification.progression),
	"[Alice] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 278, ItemClassification.progression),
	"[Alice] Stage 6A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 279, ItemClassification.progression),
	"[Alice] Stage 6B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 280, ItemClassification.progression),
	"[Sakuya] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 281, ItemClassification.progression),
	"[Sakuya] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 282, ItemClassification.progression),
	"[Sakuya] Stage 4A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 283, ItemClassification.progression),
	"[Sakuya] Stage 4B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 284, ItemClassification.progression),
	"[Sakuya] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 285, ItemClassification.progression),
	"[Sakuya] Stage 6A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 286, ItemClassification.progression),
	"[Sakuya] Stage 6B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 287, ItemClassification.progression),
	"[Remilia] Stage 2":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 288, ItemClassification.progression),
	"[Remilia] Stage 3":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 289, ItemClassification.progression),
	"[Remilia] Stage 4A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 290, ItemClassification.progression),
	"[Remilia] Stage 4B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 291, ItemClassification.progression),
	"[Remilia] Stage 5":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 292, ItemClassification.progression),
	"[Remilia] Stage 6A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 293, ItemClassification.progression),
	"[Remilia] Stage 6B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 294, ItemClassification.progression),
	"[Youmu] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 295, ItemClassification.progression),
	"[Youmu] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 296, ItemClassification.progression),
	"[Youmu] Stage 4A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 297, ItemClassification.progression),
	"[Youmu] Stage 4B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 298, ItemClassification.progression),
	"[Youmu] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 299, ItemClassification.progression),
	"[Youmu] Stage 6A":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2100, ItemClassification.progression),
	"[Youmu] Stage 6B":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2101, ItemClassification.progression),
	"[Yuyuko] Stage 2":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2102, ItemClassification.progression),
	"[Yuyuko] Stage 3":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2103, ItemClassification.progression),
	"[Yuyuko] Stage 4A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2104, ItemClassification.progression),
	"[Yuyuko] Stage 4B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2105, ItemClassification.progression),
	"[Yuyuko] Stage 5":				TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2106, ItemClassification.progression),
	"[Yuyuko] Stage 6A":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2107, ItemClassification.progression),
	"[Yuyuko] Stage 6B":			TItemData("[Not Progressive][Solo Character] Stages", STARTING_ID + 2108, ItemClassification.progression),
	"[Solo] Extra Stage":			TItemData("[Solo Character] Extra Stage", STARTING_ID + 2109, ItemClassification.progression),

	# Endings and Treasures
	"[Illusion Team] Ending - Eirin":	TItemData("Endings", STARTING_ID + 300, ItemClassification.progression),
	"[Magic Team] Ending - Eirin":		TItemData("Endings", STARTING_ID + 301, ItemClassification.progression),
	"[Devil Team] Ending - Eirin":		TItemData("Endings", STARTING_ID + 302, ItemClassification.progression),
	"[Nether Team] Ending - Eirin":		TItemData("Endings", STARTING_ID + 303, ItemClassification.progression),
	"[Illusion Team] Ending - Kaguya":	TItemData("Endings", STARTING_ID + 304, ItemClassification.progression),
	"[Magic Team] Ending - Kaguya":		TItemData("Endings", STARTING_ID + 305, ItemClassification.progression),
	"[Devil Team] Ending - Kaguya":		TItemData("Endings", STARTING_ID + 306, ItemClassification.progression),
	"[Nether Team] Ending - Kaguya":	TItemData("Endings", STARTING_ID + 307, ItemClassification.progression),
	"[Illusion Team] Ending - Mokou":	TItemData("Endings", STARTING_ID + 308, ItemClassification.progression),
	"[Magic Team] Ending - Mokou":		TItemData("Endings", STARTING_ID + 309, ItemClassification.progression),
	"[Devil Team] Ending - Mokou":		TItemData("Endings", STARTING_ID + 310, ItemClassification.progression),
	"[Nether Team] Ending - Mokou":		TItemData("Endings", STARTING_ID + 311, ItemClassification.progression),
	"Brilliant Dragon Bullet":			TItemData("Treasures", STARTING_ID + 312, ItemClassification.progression),
	"Buddhist Diamond":					TItemData("Treasures", STARTING_ID + 313, ItemClassification.progression),
	"Salamander Shield":				TItemData("Treasures", STARTING_ID + 314, ItemClassification.progression),
	"Life Spring Shield":				TItemData("Treasures", STARTING_ID + 315, ItemClassification.progression),
	"Jeweled Branch of Hourai":			TItemData("Treasures", STARTING_ID + 316, ItemClassification.progression),
	"Impossible Request Completed":		TItemData("Endings", STARTING_ID + 317, ItemClassification.progression),
	"[Reimu] Ending - Eirin":			TItemData("Endings", STARTING_ID + 318, ItemClassification.progression),
	"[Yukari] Ending - Eirin":			TItemData("Endings", STARTING_ID + 319, ItemClassification.progression),
	"[Marisa] Ending - Eirin":			TItemData("Endings", STARTING_ID + 320, ItemClassification.progression),
	"[Alice] Ending - Eirin":			TItemData("Endings", STARTING_ID + 321, ItemClassification.progression),
	"[Sakuya] Ending - Eirin":			TItemData("Endings", STARTING_ID + 322, ItemClassification.progression),
	"[Remilia] Ending - Eirin":			TItemData("Endings", STARTING_ID + 323, ItemClassification.progression),
	"[Youmu] Ending - Eirin":			TItemData("Endings", STARTING_ID + 324, ItemClassification.progression),
	"[Yuyuko] Ending - Eirin":			TItemData("Endings", STARTING_ID + 325, ItemClassification.progression),
	"[Reimu] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 326, ItemClassification.progression),
	"[Yukari] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 327, ItemClassification.progression),
	"[Marisa] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 328, ItemClassification.progression),
	"[Alice] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 329, ItemClassification.progression),
	"[Sakuya] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 330, ItemClassification.progression),
	"[Remilia] Ending - Kaguya":		TItemData("Endings", STARTING_ID + 331, ItemClassification.progression),
	"[Youmu] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 332, ItemClassification.progression),
	"[Yuyuko] Ending - Kaguya":			TItemData("Endings", STARTING_ID + 333, ItemClassification.progression),
	"[Reimu] Ending - Mokou":			TItemData("Endings", STARTING_ID + 334, ItemClassification.progression),
	"[Yukari] Ending - Mokou":			TItemData("Endings", STARTING_ID + 335, ItemClassification.progression),
	"[Marisa] Ending - Mokou":			TItemData("Endings", STARTING_ID + 336, ItemClassification.progression),
	"[Alice] Ending - Mokou":			TItemData("Endings", STARTING_ID + 337, ItemClassification.progression),
	"[Sakuya] Ending - Mokou":			TItemData("Endings", STARTING_ID + 338, ItemClassification.progression),
	"[Remilia] Ending - Mokou":			TItemData("Endings", STARTING_ID + 339, ItemClassification.progression),
	"[Youmu] Ending - Mokou":			TItemData("Endings", STARTING_ID + 340, ItemClassification.progression),
	"[Yuyuko] Ending - Mokou":			TItemData("Endings", STARTING_ID + 341, ItemClassification.progression),

	# Junk
	"+1 Power Point":	TItemData("Filler", STARTING_ID + 400),
	"+10 Time Point":	TItemData("Filler", STARTING_ID + 401),
	"+50 Time Point":	TItemData("Filler", STARTING_ID + 402),

	# Trap
	"-50% Power Point":				TItemData("Traps", STARTING_ID + 500, ItemClassification.trap),
	"-1 Bomb":						TItemData("Traps", STARTING_ID + 501, ItemClassification.trap),
	"-1 Life":						TItemData("Traps", STARTING_ID + 502, ItemClassification.trap),
	"Reverse Movement":				TItemData("Traps", STARTING_ID + 503, ItemClassification.trap),
	"Aya Speed":					TItemData("Traps", STARTING_ID + 504, ItemClassification.trap),
	"Freeze":						TItemData("Traps", STARTING_ID + 505, ItemClassification.trap),
	"Power Point Drain":			TItemData("Traps", STARTING_ID + 506, ItemClassification.trap),
	"Reverse Human/Youkai Gauge":	TItemData("Traps", STARTING_ID + 507, ItemClassification.trap),
	"Extend Time Goal":				TItemData("Traps", STARTING_ID + 508, ItemClassification.trap),

	# Spell Cards
	"001 - Firefly Sign \"Earthly Meteor\"":									TItemData("Spell Card", STARTING_ID + 6001, ItemClassification.progression),
	"002 - Firefly Sign \"Earthly Comet\"":										TItemData("Spell Card", STARTING_ID + 6002, ItemClassification.progression),
	"003 - Lamp Sign \"Firefly Phenomenon\"":									TItemData("Spell Card", STARTING_ID + 6003, ItemClassification.progression),
	"004 - Lamp Sign \"Firefly Phenomenon\"":									TItemData("Spell Card", STARTING_ID + 6004, ItemClassification.progression),
	"005 - Lamp Sign \"Firefly Phenomenon\"":									TItemData("Spell Card", STARTING_ID + 6005, ItemClassification.progression),
	"006 - Lamp Sign \"Firefly Phenomenon\"":									TItemData("Spell Card", STARTING_ID + 6006, ItemClassification.progression),
	"007 - Wriggle Sign \"Little Bug\"":										TItemData("Spell Card", STARTING_ID + 6007, ItemClassification.progression),
	"008 - Wriggle Sign \"Little Bug Storm\"":									TItemData("Spell Card", STARTING_ID + 6008, ItemClassification.progression),
	"009 - Wriggle Sign \"Nightbug Storm\"":									TItemData("Spell Card", STARTING_ID + 6009, ItemClassification.progression),
	"010 - Wriggle Sign \"Nightbug Tornado\"":									TItemData("Spell Card", STARTING_ID + 6010, ItemClassification.progression),
	"011 - Hidden Bug \"Endless Night Seclusion\"":								TItemData("Spell Card", STARTING_ID + 6011, ItemClassification.progression),
	"012 - Hidden Bug \"Endless Night Seclusion\"":								TItemData("Spell Card", STARTING_ID + 6012, ItemClassification.progression),
	"013 - Hidden Bug \"Endless Night Seclusion\"":								TItemData("Spell Card", STARTING_ID + 6013, ItemClassification.progression),
	"014 - Vocal Sign \"Hooting in the Night\"":								TItemData("Spell Card", STARTING_ID + 6014, ItemClassification.progression),
	"015 - Vocal Sign \"Hooting in the Night\"":								TItemData("Spell Card", STARTING_ID + 6015, ItemClassification.progression),
	"016 - Vocal Sign \"Howl of the Horned Owl\"":								TItemData("Spell Card", STARTING_ID + 6016, ItemClassification.progression),
	"017 - Vocal Sign \"Howl of the Horned Owl\"":								TItemData("Spell Card", STARTING_ID + 6017, ItemClassification.progression),
	"018 - Moth Sign \"Hawk Moth's Insect Curse\"":								TItemData("Spell Card", STARTING_ID + 6018, ItemClassification.progression),
	"019 - Moth Sign \"Hawk Moth's Insect Curse\"":								TItemData("Spell Card", STARTING_ID + 6019, ItemClassification.progression),
	"020 - Toxin Sign \"Poisonous Moth's Scales\"":								TItemData("Spell Card", STARTING_ID + 6020, ItemClassification.progression),
	"021 - Deadly Toxin Sign \"Poisonous Moth's Dance in the Dark\"":			TItemData("Spell Card", STARTING_ID + 6021, ItemClassification.progression),
	"022 - Hawk Sign \"Ill Starred Dive\"":										TItemData("Spell Card", STARTING_ID + 6022, ItemClassification.progression),
	"023 - Hawk Sign \"Ill Starred Dive\"":										TItemData("Spell Card", STARTING_ID + 6023, ItemClassification.progression),
	"024 - Hawk Sign \"Ill Starred Dive\"":										TItemData("Spell Card", STARTING_ID + 6024, ItemClassification.progression),
	"025 - Hawk Sign \"Ill Starred Dive\"":										TItemData("Spell Card", STARTING_ID + 6025, ItemClassification.progression),
	"026 - Night-Blindness \"Song of the Night Sparrow\"":						TItemData("Spell Card", STARTING_ID + 6026, ItemClassification.progression),
	"027 - Night-Blindness \"Song of the Night Sparrow\"":						TItemData("Spell Card", STARTING_ID + 6027, ItemClassification.progression),
	"028 - Night-Blindness \"Song of the Night Sparrow\"":						TItemData("Spell Card", STARTING_ID + 6028, ItemClassification.progression),
	"029 - Night-Blindness \"Song of the Night Sparrow\"":						TItemData("Spell Card", STARTING_ID + 6029, ItemClassification.progression),
	"030 - Night-Sparrow \"Midnight Chorus Master\"":							TItemData("Spell Card", STARTING_ID + 6030, ItemClassification.progression),
	"031 - Night-Sparrow \"Midnight Chorus Master\"":							TItemData("Spell Card", STARTING_ID + 6031, ItemClassification.progression),
	"032 - Night-Sparrow \"Midnight Chorus Master\"":							TItemData("Spell Card", STARTING_ID + 6032, ItemClassification.progression),
	"033 - Spiritual Birth \"First Pyramid\"":									TItemData("Spell Card", STARTING_ID + 6033, ItemClassification.progression),
	"034 - Spiritual Birth \"First Pyramid\"":									TItemData("Spell Card", STARTING_ID + 6034, ItemClassification.progression),
	"035 - Spiritual Birth \"First Pyramid\"":									TItemData("Spell Card", STARTING_ID + 6035, ItemClassification.progression),
	"036 - Spiritual Birth \"First Pyramid\"":									TItemData("Spell Card", STARTING_ID + 6036, ItemClassification.progression),
	"037 - Origin Sign \"Ephemerality 137\"":									TItemData("Spell Card", STARTING_ID + 6037, ItemClassification.progression),
	"038 - Origin Sign \"Ephemerality 137\"":									TItemData("Spell Card", STARTING_ID + 6038, ItemClassification.progression),
	"039 - Origin Sign \"Ephemerality 137\"":									TItemData("Spell Card", STARTING_ID + 6039, ItemClassification.progression),
	"040 - Ambition Sign \"Buretsu Crisis\"":									TItemData("Spell Card", STARTING_ID + 6040, ItemClassification.progression),
	"041 - Ambition Sign \"Masakado Crisis\"":									TItemData("Spell Card", STARTING_ID + 6041, ItemClassification.progression),
	"042 - Ambition Sign \"Yoshimitsu Crisis\"":								TItemData("Spell Card", STARTING_ID + 6042, ItemClassification.progression),
	"043 - Ambition Sign \"General Headquarters Crisis\"":						TItemData("Spell Card", STARTING_ID + 6043, ItemClassification.progression),
	"044 - Land Sign \"Three Sacred Treasures - Sword\"":						TItemData("Spell Card", STARTING_ID + 6044, ItemClassification.progression),
	"045 - Land Sign \"Three Sacred Treasures - Orb\"":							TItemData("Spell Card", STARTING_ID + 6045, ItemClassification.progression),
	"046 - Land Sign \"Three Sacred Treasures - Mirror\"":						TItemData("Spell Card", STARTING_ID + 6046, ItemClassification.progression),
	"047 - Land Sign \"Three Sacred Treasures - Country\"":						TItemData("Spell Card", STARTING_ID + 6047, ItemClassification.progression),
	"048 - Ending Sign \"Phantasmal Emperor\"":									TItemData("Spell Card", STARTING_ID + 6048, ItemClassification.progression),
	"049 - Ending Sign \"Phantasmal Emperor\"":									TItemData("Spell Card", STARTING_ID + 6049, ItemClassification.progression),
	"050 - Pseudo-History \"The Legend of Gensokyo\"":							TItemData("Spell Card", STARTING_ID + 6050, ItemClassification.progression),
	"051 - Pseudo-History \"The Legend of Gensokyo\"":							TItemData("Spell Card", STARTING_ID + 6051, ItemClassification.progression),
	"052 - Future \"Gods' Realm\"":												TItemData("Spell Card", STARTING_ID + 6052, ItemClassification.progression),
	"053 - Future \"Gods' Realm\"":												TItemData("Spell Card", STARTING_ID + 6053, ItemClassification.progression),
	"054 - Future \"Gods' Realm\"":												TItemData("Spell Card", STARTING_ID + 6054, ItemClassification.progression),
	"055 - Dream Sign \"Duplex Barrier\"":										TItemData("Spell Card", STARTING_ID + 6055, ItemClassification.progression),
	"056 - Dream Sign \"Duplex Barrier\"":										TItemData("Spell Card", STARTING_ID + 6056, ItemClassification.progression),
	"057 - Dream Land \"Great Duplex Barrier\"":								TItemData("Spell Card", STARTING_ID + 6057, ItemClassification.progression),
	"058 - Dream Land \"Great Duplex Barrier\"":								TItemData("Spell Card", STARTING_ID + 6058, ItemClassification.progression),
	"059 - Spirit Sign \"Fantasy Seal -Spread-\"":								TItemData("Spell Card", STARTING_ID + 6059, ItemClassification.progression),
	"060 - Spirit Sign \"Fantasy Seal -Spread-\"":					 			TItemData("Spell Card", STARTING_ID + 6060, ItemClassification.progression),
	"061 - Scattered Sign \"Fantasy Seal -Worn-\"":					 			TItemData("Spell Card", STARTING_ID + 6061, ItemClassification.progression),
	"062 - Scattered Sign \"Fantasy Seal -Worn-\"":					 			TItemData("Spell Card", STARTING_ID + 6062, ItemClassification.progression),
	"063 - Dream Sign \"Evil-Sealing Circle\"":									TItemData("Spell Card", STARTING_ID + 6063, ItemClassification.progression),
	"064 - Dream Sign \"Evil-Sealing Circle\"":									TItemData("Spell Card", STARTING_ID + 6064, ItemClassification.progression),
	"065 - Divine Arts \"Omnidirectional Oni-Binding Circle\"":					TItemData("Spell Card", STARTING_ID + 6065, ItemClassification.progression),
	"066 - Divine Arts \"Omnidirectional Dragon-Slaying Circle\"":				TItemData("Spell Card", STARTING_ID + 6066, ItemClassification.progression),
	"067 - Spirit Sign \"Fantasy Seal -Concentrate-\"":							TItemData("Spell Card", STARTING_ID + 6067, ItemClassification.progression),
	"068 - Spirit Sign \"Fantasy Seal -Concentrate-\"":							TItemData("Spell Card", STARTING_ID + 6068, ItemClassification.progression),
	"069 - Migrating Spirit \"Fantasy Seal -Marred-\"":							TItemData("Spell Card", STARTING_ID + 6069, ItemClassification.progression),
	"070 - Migrating Spirit \"Fantasy Seal -Marred-\"":							TItemData("Spell Card", STARTING_ID + 6070, ItemClassification.progression),
	"071 - Boundary \"Duplex Danmaku Barrier\"":								TItemData("Spell Card", STARTING_ID + 6071, ItemClassification.progression),
	"072 - Boundary \"Duplex Danmaku Barrier\"":								TItemData("Spell Card", STARTING_ID + 6072, ItemClassification.progression),
	"073 - Great Barrier \"Hakurei Danmaku Barrier\"":							TItemData("Spell Card", STARTING_ID + 6073, ItemClassification.progression),
	"074 - Great Barrier \"Hakurei Danmaku Barrier\"":							TItemData("Spell Card", STARTING_ID + 6074, ItemClassification.progression),
	"075 - Divine Spirit \"Fantasy Seal -Blink-\"":								TItemData("Spell Card", STARTING_ID + 6075, ItemClassification.progression),
	"076 - Divine Spirit \"Fantasy Seal -Blink-\"":								TItemData("Spell Card", STARTING_ID + 6076, ItemClassification.progression),
	"077 - Divine Spirit \"Fantasy Seal -Blink-\"":								TItemData("Spell Card", STARTING_ID + 6077, ItemClassification.progression),
	"078 - Magic Sign \"Milky Way\"":											TItemData("Spell Card", STARTING_ID + 6078, ItemClassification.progression),
	"079 - Magic Sign \"Milky Way\"":											TItemData("Spell Card", STARTING_ID + 6079, ItemClassification.progression),
	"080 - Magic Space \"Asteroid Belt\"":										TItemData("Spell Card", STARTING_ID + 6080, ItemClassification.progression),
	"081 - Magic Space \"Asteroid Belt\"":										TItemData("Spell Card", STARTING_ID + 6081, ItemClassification.progression),
	"082 - Magic Sign \"Stardust Reverie\"":									TItemData("Spell Card", STARTING_ID + 6082, ItemClassification.progression),
	"083 - Magic Sign \"Stardust Reverie\"":									TItemData("Spell Card", STARTING_ID + 6083, ItemClassification.progression),
	"084 - Black Magic \"Event Horizon\"":										TItemData("Spell Card", STARTING_ID + 6084, ItemClassification.progression),
	"085 - Black Magic \"Event Horizon\"":										TItemData("Spell Card", STARTING_ID + 6085, ItemClassification.progression),
	"086 - Love Sign \"Non-Directional Laser\"":								TItemData("Spell Card", STARTING_ID + 6086, ItemClassification.progression),
	"087 - Love Sign \"Non-Directional Laser\"":								TItemData("Spell Card", STARTING_ID + 6087, ItemClassification.progression),
	"088 - Love Storm \"Starlight Typhoon\"":									TItemData("Spell Card", STARTING_ID + 6088, ItemClassification.progression),
	"089 - Love Storm \"Starlight Typhoon\"":									TItemData("Spell Card", STARTING_ID + 6089, ItemClassification.progression),
	"090 - Love Sign \"Master Spark\"":											TItemData("Spell Card", STARTING_ID + 6090, ItemClassification.progression),
	"091 - Love Sign \"Master Spark\"":											TItemData("Spell Card", STARTING_ID + 6091, ItemClassification.progression),
	"092 - Loving Heart \"Double Spark\"":										TItemData("Spell Card", STARTING_ID + 6092, ItemClassification.progression),
	"093 - Loving Heart \"Double Spark\"":										TItemData("Spell Card", STARTING_ID + 6093, ItemClassification.progression),
	"094 - Light Sign \"Earthlight Ray\"":										TItemData("Spell Card", STARTING_ID + 6094, ItemClassification.progression),
	"095 - Light Sign \"Earthlight Ray\"":										TItemData("Spell Card", STARTING_ID + 6095, ItemClassification.progression),
	"096 - Light Blast \"Shoot the Moon\"":										TItemData("Spell Card", STARTING_ID + 6096, ItemClassification.progression),
	"097 - Light Blast \"Shoot the Moon\"":										TItemData("Spell Card", STARTING_ID + 6097, ItemClassification.progression),
	"098 - Magicannon \"Final Spark\"":											TItemData("Spell Card", STARTING_ID + 6098, ItemClassification.progression),
	"099 - Magicannon \"Final Spark\"":											TItemData("Spell Card", STARTING_ID + 6099, ItemClassification.progression),
	"100 - Magicannon \"Final Master Spark\"":									TItemData("Spell Card", STARTING_ID + 6100, ItemClassification.progression),
	"101 - Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"":						TItemData("Spell Card", STARTING_ID + 6101, ItemClassification.progression),
	"102 - Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\"":						TItemData("Spell Card", STARTING_ID + 6102, ItemClassification.progression),
	"103 - Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"":					TItemData("Spell Card", STARTING_ID + 6103, ItemClassification.progression),
	"104 - Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\"":					TItemData("Spell Card", STARTING_ID + 6104, ItemClassification.progression),
	"105 - Lunatic Sign \"Hallucination Tuning (Visionary Tuning)\"":			TItemData("Spell Card", STARTING_ID + 6105, ItemClassification.progression),
	"106 - Lunatic Sign \"Hallucination Tuning (Visionary Tuning)\"":			TItemData("Spell Card", STARTING_ID + 6106, ItemClassification.progression),
	"107 - Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"":			TItemData("Spell Card", STARTING_ID + 6107, ItemClassification.progression),
	"108 - Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\"":			TItemData("Spell Card", STARTING_ID + 6108, ItemClassification.progression),
	"109 - Loafing Sign \"Life & Spirit Stopping (Idling Wave)\"":				TItemData("Spell Card", STARTING_ID + 6109, ItemClassification.progression),
	"110 - Loafing Sign \"Life & Spirit Stopping (Idling Wave)\"":				TItemData("Spell Card", STARTING_ID + 6110, ItemClassification.progression),
	"111 - Indolence \"Life & Spirit Stopping (Mind Stopper)\"":				TItemData("Spell Card", STARTING_ID + 6111, ItemClassification.progression),
	"112 - Indolence \"Life & Spirit Stopping (Mind Stopper)\"":				TItemData("Spell Card", STARTING_ID + 6112, ItemClassification.progression),
	"113 - Spread Sign \"Moon of Truth (Invisible Full Moon)\"":				TItemData("Spell Card", STARTING_ID + 6113, ItemClassification.progression),
	"114 - Spread Sign \"Moon of Truth (Invisible Full Moon)\"":				TItemData("Spell Card", STARTING_ID + 6114, ItemClassification.progression),
	"115 - Spread Sign \"Moon of Truth (Invisible Full Moon)\"":				TItemData("Spell Card", STARTING_ID + 6115, ItemClassification.progression),
	"116 - Spread Sign \"Moon of Truth (Invisible Full Moon)\"":				TItemData("Spell Card", STARTING_ID + 6116, ItemClassification.progression),
	"117 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"":	TItemData("Spell Card", STARTING_ID + 6117, ItemClassification.progression),
	"118 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"":	TItemData("Spell Card", STARTING_ID + 6118, ItemClassification.progression),
	"119 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\"":	TItemData("Spell Card", STARTING_ID + 6119, ItemClassification.progression),
	"120 - Spacesphere \"Earth in a Pot\"":										TItemData("Spell Card", STARTING_ID + 6120, ItemClassification.progression),
	"121 - Spacesphere \"Earth in a Pot\"":										TItemData("Spell Card", STARTING_ID + 6121, ItemClassification.progression),
	"122 - Spacesphere \"Earth in a Pot\"":										TItemData("Spell Card", STARTING_ID + 6122, ItemClassification.progression),
	"123 - Spacesphere \"Earth in a Pot\"":										TItemData("Spell Card", STARTING_ID + 6123, ItemClassification.progression),
	"124 - Awakened God \"Memories of the Age of the Gods\"":					TItemData("Spell Card", STARTING_ID + 6124, ItemClassification.progression),
	"125 - Awakened God \"Memories of the Age of the Gods\"":					TItemData("Spell Card", STARTING_ID + 6125, ItemClassification.progression),
	"126 - God Sign \"Genealogy of the Celestials\"":							TItemData("Spell Card", STARTING_ID + 6126, ItemClassification.progression),
	"127 - God Sign \"Genealogy of the Celestials\"":							TItemData("Spell Card", STARTING_ID + 6127, ItemClassification.progression),
	"128 - Revival \"Seimei Yugi -Life Game-\"":								TItemData("Spell Card", STARTING_ID + 6128, ItemClassification.progression),
	"129 - Revival \"Seimei Yugi -Life Game-\"":								TItemData("Spell Card", STARTING_ID + 6129, ItemClassification.progression),
	"130 - Resurrection \"Rising Game\"":										TItemData("Spell Card", STARTING_ID + 6130, ItemClassification.progression),
	"131 - Resurrection \"Rising Game\"":										TItemData("Spell Card", STARTING_ID + 6131, ItemClassification.progression),
	"132 - Leading God \"Omoikane's Device\"":									TItemData("Spell Card", STARTING_ID + 6132, ItemClassification.progression),
	"133 - Leading God \"Omoikane's Device\"":									TItemData("Spell Card", STARTING_ID + 6133, ItemClassification.progression),
	"134 - Mind of God \"Omoikane's Brain\"":									TItemData("Spell Card", STARTING_ID + 6134, ItemClassification.progression),
	"135 - Mind of God \"Omoikane's Brain\"":									TItemData("Spell Card", STARTING_ID + 6135, ItemClassification.progression),
	"136 - Curse of the Heavens \"Apollo 13\"":									TItemData("Spell Card", STARTING_ID + 6136, ItemClassification.progression),
	"137 - Curse of the Heavens \"Apollo 13\"":									TItemData("Spell Card", STARTING_ID + 6137, ItemClassification.progression),
	"138 - Curse of the Heavens \"Apollo 13\"":									TItemData("Spell Card", STARTING_ID + 6138, ItemClassification.progression),
	"139 - Curse of the Heavens \"Apollo 13\"":									TItemData("Spell Card", STARTING_ID + 6139, ItemClassification.progression),
	"140 - Esoterica \"Astronomical Cover-Up\"":								TItemData("Spell Card", STARTING_ID + 6140, ItemClassification.progression),
	"141 - Esoterica \"Astronomical Cover-Up\"":								TItemData("Spell Card", STARTING_ID + 6141, ItemClassification.progression),
	"142 - Esoterica \"Astronomical Cover-Up\"":								TItemData("Spell Card", STARTING_ID + 6142, ItemClassification.progression),
	"143 - Esoterica \"Astronomical Cover-Up\"":								TItemData("Spell Card", STARTING_ID + 6143, ItemClassification.progression),
	"144 - Forbidden Elixir \"Hourai Elixir\"":									TItemData("Spell Card", STARTING_ID + 6144, ItemClassification.progression),
	"145 - Forbidden Elixir \"Hourai Elixir\"":									TItemData("Spell Card", STARTING_ID + 6145, ItemClassification.progression),
	"146 - Forbidden Elixir \"Hourai Elixir\"":									TItemData("Spell Card", STARTING_ID + 6146, ItemClassification.progression),
	"147 - Forbidden Elixir \"Hourai Elixir\"":									TItemData("Spell Card", STARTING_ID + 6147, ItemClassification.progression),
	"148 - Medicine Sign \"Galaxy in a Pot\"":									TItemData("Spell Card", STARTING_ID + 6148, ItemClassification.progression),
	"149 - Medicine Sign \"Galaxy in a Pot\"":									TItemData("Spell Card", STARTING_ID + 6149, ItemClassification.progression),
	"150 - Medicine Sign \"Galaxy in a Pot\"":									TItemData("Spell Card", STARTING_ID + 6150, ItemClassification.progression),
	"151 - Medicine Sign \"Galaxy in a Pot\"":									TItemData("Spell Card", STARTING_ID + 6151, ItemClassification.progression),
	"152 - Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"":	TItemData("Spell Card", STARTING_ID + 6152, ItemClassification.progression),
	"153 - Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\"":	TItemData("Spell Card", STARTING_ID + 6153, ItemClassification.progression),
	"154 - Divine Treasure \"Brilliant Dragon Bullet\"":						TItemData("Spell Card", STARTING_ID + 6154, ItemClassification.progression),
	"155 - Divine Treasure \"Brilliant Dragon Bullet\"":						TItemData("Spell Card", STARTING_ID + 6155, ItemClassification.progression),
	"156 - Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"":		TItemData("Spell Card", STARTING_ID + 6156, ItemClassification.progression),
	"157 - Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\"":		TItemData("Spell Card", STARTING_ID + 6157, ItemClassification.progression),
	"158 - Divine Treasure \"Buddhist Diamond\"":								TItemData("Spell Card", STARTING_ID + 6158, ItemClassification.progression),
	"159 - Divine Treasure \"Buddhist Diamond\"":								TItemData("Spell Card", STARTING_ID + 6159, ItemClassification.progression),
	"160 - Impossible Request \"Robe of Fire Rat -Patient Mind-\"":				TItemData("Spell Card", STARTING_ID + 6160, ItemClassification.progression),
	"161 - Impossible Request \"Robe of Fire Rat -Patient Mind-\"":				TItemData("Spell Card", STARTING_ID + 6161, ItemClassification.progression),
	"162 - Divine Treasure \"Salamander Shield\"":								TItemData("Spell Card", STARTING_ID + 6162, ItemClassification.progression),
	"163 - Divine Treasure \"Salamander Shield\"":								TItemData("Spell Card", STARTING_ID + 6163, ItemClassification.progression),
	"164 - Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"":	TItemData("Spell Card", STARTING_ID + 6164, ItemClassification.progression),
	"165 - Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\"":	TItemData("Spell Card", STARTING_ID + 6165, ItemClassification.progression),
	"166 - Divine Treasure \"Life Spring Infinity\"":							TItemData("Spell Card", STARTING_ID + 6166, ItemClassification.progression),
	"167 - Divine Treasure \"Life Spring Infinity\"":							TItemData("Spell Card", STARTING_ID + 6167, ItemClassification.progression),
	"168 - Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\"":	TItemData("Spell Card", STARTING_ID + 6168, ItemClassification.progression),
	"169 - Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\"":	TItemData("Spell Card", STARTING_ID + 6169, ItemClassification.progression),
	"170 - Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"":	TItemData("Spell Card", STARTING_ID + 6170, ItemClassification.progression),
	"171 - Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\"":	TItemData("Spell Card", STARTING_ID + 6171, ItemClassification.progression),
	"172 - End of Imperishable Night -New Moon-":								TItemData("Spell Card", STARTING_ID + 6172, ItemClassification.progression),
	"173 - End of Imperishable Night -Crescent Moon-":							TItemData("Spell Card", STARTING_ID + 6173, ItemClassification.progression),
	"174 - End of Imperishable Night -1st Quarter's Moon-":						TItemData("Spell Card", STARTING_ID + 6174, ItemClassification.progression),
	"175 - End of Imperishable Night -Matsuyoi-":								TItemData("Spell Card", STARTING_ID + 6175, ItemClassification.progression),
	"176 - End of Imperishable Night -11 o'Clock-":								TItemData("Spell Card", STARTING_ID + 6176, ItemClassification.progression),
	"177 - End of Imperishable Night -Half of Midnight-":						TItemData("Spell Card", STARTING_ID + 6177, ItemClassification.progression),
	"178 - End of Imperishable Night -Midnight-":								TItemData("Spell Card", STARTING_ID + 6178, ItemClassification.progression),
	"179 - End of Imperishable Night -Half Past Midnight-":						TItemData("Spell Card", STARTING_ID + 6179, ItemClassification.progression),
	"180 - End of Imperishable Night -1 o'Clock-":								TItemData("Spell Card", STARTING_ID + 6180, ItemClassification.progression),
	"181 - End of Imperishable Night -Half Past 1-":							TItemData("Spell Card", STARTING_ID + 6181, ItemClassification.progression),
	"182 - End of Imperishable Night -Dead of Night-":							TItemData("Spell Card", STARTING_ID + 6182, ItemClassification.progression),
	"183 - End of Imperishable Night -Half Past 2-":							TItemData("Spell Card", STARTING_ID + 6183, ItemClassification.progression),
	"184 - End of Imperishable Night -3 o'Clock-":								TItemData("Spell Card", STARTING_ID + 6184, ItemClassification.progression),
	"185 - End of Imperishable Night -Half Past 3-":							TItemData("Spell Card", STARTING_ID + 6185, ItemClassification.progression),
	"186 - End of Imperishable Night -4 o'Clock-":								TItemData("Spell Card", STARTING_ID + 6186, ItemClassification.progression),
	"187 - End of Imperishable Night -Half Past 4-":							TItemData("Spell Card", STARTING_ID + 6187, ItemClassification.progression),
	"188 - End of Imperishable Night -Morning Mist-":							TItemData("Spell Card", STARTING_ID + 6188, ItemClassification.progression),
	"189 - End of Imperishable Night -Dawn-":									TItemData("Spell Card", STARTING_ID + 6189, ItemClassification.progression),
	"190 - End of Imperishable Night -Morning Star-":							TItemData("Spell Card", STARTING_ID + 6190, ItemClassification.progression),
	"191 - End of Imperishable Night -Rising World-":							TItemData("Spell Card", STARTING_ID + 6191, ItemClassification.progression),
	"192 - Past \"Old History of an Untrodden Land -Old History-\"":			TItemData("Spell Card", STARTING_ID + 6192, ItemClassification.progression),
	"193 - Reincarnation \"Ichijou Returning Bridge\"":							TItemData("Spell Card", STARTING_ID + 6193, ItemClassification.progression),
	"194 - Future \"New History of Fantasy -Next History-\"":					TItemData("Spell Card", STARTING_ID + 6194, ItemClassification.progression),
	"195 - Statute of Limitations \"Curse of Tsuki no Iwakasa\"":				TItemData("Spell Card", STARTING_ID + 6195, ItemClassification.progression),
	"196 - Undying \"Fire Bird -Feng Wing Ascension-\"":						TItemData("Spell Card", STARTING_ID + 6196, ItemClassification.progression),
	"197 - Fujiwara \"Wounds of Metsuzai Temple\"":								TItemData("Spell Card", STARTING_ID + 6197, ItemClassification.progression),
	"198 - Undying \"Xu Fu's Dimension\"":										TItemData("Spell Card", STARTING_ID + 6198, ItemClassification.progression),
	"199 - Expiation \"Honest Man's Death\"":									TItemData("Spell Card", STARTING_ID + 6199, ItemClassification.progression),
	"200 - Hollow Being \"Wu\"":												TItemData("Spell Card", STARTING_ID + 6200, ItemClassification.progression),
	"201 - Inextinguishable \"Phoenix's Tail\"":								TItemData("Spell Card", STARTING_ID + 6201, ItemClassification.progression),
	"202 - Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\"":				TItemData("Spell Card", STARTING_ID + 6202, ItemClassification.progression),
	"203 - \"Possessed by Phoenix\"":											TItemData("Spell Card", STARTING_ID + 6203, ItemClassification.progression),
	"204 - \"Hourai Doll\"":													TItemData("Spell Card", STARTING_ID + 6204, ItemClassification.progression),
	"205 - \"Imperishable Shooting\"":											TItemData("Spell Card", STARTING_ID + 6205, ItemClassification.progression),
	"206 - \"Unseasonal Butterfly Storm\"":										TItemData("Spell Card", STARTING_ID + 6206, ItemClassification.progression),
	"207 - \"Blind Nightbird\"":												TItemData("Spell Card", STARTING_ID + 6207, ItemClassification.progression),
	"208 - \"Emperor of the Land of the Rising Sun\"":							TItemData("Spell Card", STARTING_ID + 6208, ItemClassification.progression),
	"209 - \"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"":				TItemData("Spell Card", STARTING_ID + 6209, ItemClassification.progression),
	"210 - \"Heaven Spider's Butterfly-Capturing Web\"":						TItemData("Spell Card", STARTING_ID + 6210, ItemClassification.progression),
	"211 - \"Hourai's Sea of Trees\"":											TItemData("Spell Card", STARTING_ID + 6211, ItemClassification.progression),
	"212 - \"Phoenix Rebirth\"":												TItemData("Spell Card", STARTING_ID + 6212, ItemClassification.progression),
	"213 - \"Ancient Duper\"":													TItemData("Spell Card", STARTING_ID + 6213, ItemClassification.progression),
	"214 - \"Total Purification\"":												TItemData("Spell Card", STARTING_ID + 6214, ItemClassification.progression),
	"215 - \"Fantasy Nature\"":													TItemData("Spell Card", STARTING_ID + 6215, ItemClassification.progression),
	"216 - \"Blazing Star\"":													TItemData("Spell Card", STARTING_ID + 6216, ItemClassification.progression),
	"217 - \"Deflation World\"":												TItemData("Spell Card", STARTING_ID + 6217, ItemClassification.progression),
	"218 - \"Matsuyoi-Reflecting Satellite Slash\"":							TItemData("Spell Card", STARTING_ID + 6218, ItemClassification.progression),
	"219 - \"The Phantom of the Grand Guignol\"":								TItemData("Spell Card", STARTING_ID + 6219, ItemClassification.progression),
	"220 - \"Scarlet Destiny\"":												TItemData("Spell Card", STARTING_ID + 6220, ItemClassification.progression),
	"221 - \"Saigyouji Parinirvana\"":											TItemData("Spell Card", STARTING_ID + 6221, ItemClassification.progression),
	"222 - \"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-\"":			TItemData("Spell Card", STARTING_ID + 6222, ItemClassification.progression),
}

item_groups: Dict[str, str] = {
	"Illusion Team": ["Illusionary Barrier Team"],
	"Magic Team": ["Aria of Forbidden Magic Team"],
	"Devil Team": ["Visionary Scarlet Devil Team"],
	"Nether Team": ["Netherworld Dwellers Team"],
	"Treasures": get_items_by_category("Treasures").keys(),
	"SC001": ["001 - Firefly Sign \"Earthly Meteor\""],
	"SC002": ["002 - Firefly Sign \"Earthly Comet\""],
	"SC003": ["003 - Lamp Sign \"Firefly Phenomenon\""],
	"SC004": ["004 - Lamp Sign \"Firefly Phenomenon\""],
	"SC005": ["005 - Lamp Sign \"Firefly Phenomenon\""],
	"SC006": ["006 - Lamp Sign \"Firefly Phenomenon\""],
	"SC007": ["007 - Wriggle Sign \"Little Bug\""],
	"SC008": ["008 - Wriggle Sign \"Little Bug Storm\""],
	"SC009": ["009 - Wriggle Sign \"Nightbug Storm\""],
	"SC010": ["010 - Wriggle Sign \"Nightbug Tornado\""],
	"SC011": ["011 - Hidden Bug \"Endless Night Seclusion\""],
	"SC012": ["012 - Hidden Bug \"Endless Night Seclusion\""],
	"SC013": ["013 - Hidden Bug \"Endless Night Seclusion\""],
	"SC014": ["014 - Vocal Sign \"Hooting in the Night\""],
	"SC015": ["015 - Vocal Sign \"Hooting in the Night\""],
	"SC016": ["016 - Vocal Sign \"Howl of the Horned Owl\""],
	"SC017": ["017 - Vocal Sign \"Howl of the Horned Owl\""],
	"SC018": ["018 - Moth Sign \"Hawk Moth's Insect Curse\""],
	"SC019": ["019 - Moth Sign \"Hawk Moth's Insect Curse\""],
	"SC020": ["020 - Toxin Sign \"Poisonous Moth's Scales\""],
	"SC021": ["021 - Deadly Toxin Sign \"Poisonous Moth's Dance in the Dark\""],
	"SC022": ["022 - Hawk Sign \"Ill Starred Dive\""],
	"SC023": ["023 - Hawk Sign \"Ill Starred Dive\""],
	"SC024": ["024 - Hawk Sign \"Ill Starred Dive\""],
	"SC025": ["025 - Hawk Sign \"Ill Starred Dive\""],
	"SC026": ["026 - Night-Blindness \"Song of the Night Sparrow\""],
	"SC027": ["027 - Night-Blindness \"Song of the Night Sparrow\""],
	"SC028": ["028 - Night-Blindness \"Song of the Night Sparrow\""],
	"SC029": ["029 - Night-Blindness \"Song of the Night Sparrow\""],
	"SC030": ["030 - Night-Sparrow \"Midnight Chorus Master\""],
	"SC031": ["031 - Night-Sparrow \"Midnight Chorus Master\""],
	"SC032": ["032 - Night-Sparrow \"Midnight Chorus Master\""],
	"SC033": ["033 - Spiritual Birth \"First Pyramid\""],
	"SC034": ["034 - Spiritual Birth \"First Pyramid\""],
	"SC035": ["035 - Spiritual Birth \"First Pyramid\""],
	"SC036": ["036 - Spiritual Birth \"First Pyramid\""],
	"SC037": ["037 - Origin Sign \"Ephemerality 137\""],
	"SC038": ["038 - Origin Sign \"Ephemerality 137\""],
	"SC039": ["039 - Origin Sign \"Ephemerality 137\""],
	"SC040": ["040 - Ambition Sign \"Buretsu Crisis\""],
	"SC041": ["041 - Ambition Sign \"Masakado Crisis\""],
	"SC042": ["042 - Ambition Sign \"Yoshimitsu Crisis\""],
	"SC043": ["043 - Ambition Sign \"General Headquarters Crisis\""],
	"SC044": ["044 - Land Sign \"Three Sacred Treasures - Sword\""],
	"SC045": ["045 - Land Sign \"Three Sacred Treasures - Orb\""],
	"SC046": ["046 - Land Sign \"Three Sacred Treasures - Mirror\""],
	"SC047": ["047 - Land Sign \"Three Sacred Treasures - Country\""],
	"SC048": ["048 - Ending Sign \"Phantasmal Emperor\""],
	"SC049": ["049 - Ending Sign \"Phantasmal Emperor\""],
	"SC050": ["050 - Pseudo-History \"The Legend of Gensokyo\""],
	"SC051": ["051 - Pseudo-History \"The Legend of Gensokyo\""],
	"SC052": ["052 - Future \"Gods' Realm\""],
	"SC053": ["053 - Future \"Gods' Realm\""],
	"SC054": ["054 - Future \"Gods' Realm\""],
	"SC055": ["055 - Dream Sign \"Duplex Barrier\""],
	"SC056": ["056 - Dream Sign \"Duplex Barrier\""],
	"SC057": ["057 - Dream Land \"Great Duplex Barrier\""],
	"SC058": ["058 - Dream Land \"Great Duplex Barrier\""],
	"SC059": ["059 - Spirit Sign \"Fantasy Seal -Spread-\""],
	"SC060": ["060 - Spirit Sign \"Fantasy Seal -Spread-\""],
	"SC061": ["061 - Scattered Sign \"Fantasy Seal -Worn-\""],
	"SC062": ["062 - Scattered Sign \"Fantasy Seal -Worn-\""],
	"SC063": ["063 - Dream Sign \"Evil-Sealing Circle\""],
	"SC064": ["064 - Dream Sign \"Evil-Sealing Circle\""],
	"SC065": ["065 - Divine Arts \"Omnidirectional Oni-Binding Circle\""],
	"SC066": ["066 - Divine Arts \"Omnidirectional Dragon-Slaying Circle\""],
	"SC067": ["067 - Spirit Sign \"Fantasy Seal -Concentrate-\""],
	"SC068": ["068 - Spirit Sign \"Fantasy Seal -Concentrate-\""],
	"SC069": ["069 - Migrating Spirit \"Fantasy Seal -Marred-\""],
	"SC070": ["070 - Migrating Spirit \"Fantasy Seal -Marred-\""],
	"SC071": ["071 - Boundary \"Duplex Danmaku Barrier\""],
	"SC072": ["072 - Boundary \"Duplex Danmaku Barrier\""],
	"SC073": ["073 - Great Barrier \"Hakurei Danmaku Barrier\""],
	"SC074": ["074 - Great Barrier \"Hakurei Danmaku Barrier\""],
	"SC075": ["075 - Divine Spirit \"Fantasy Seal -Blink-\""],
	"SC076": ["076 - Divine Spirit \"Fantasy Seal -Blink-\""],
	"SC077": ["077 - Divine Spirit \"Fantasy Seal -Blink-\""],
	"SC078": ["078 - Magic Sign \"Milky Way\""],
	"SC079": ["079 - Magic Sign \"Milky Way\""],
	"SC080": ["080 - Magic Space \"Asteroid Belt\""],
	"SC081": ["081 - Magic Space \"Asteroid Belt\""],
	"SC082": ["082 - Magic Sign \"Stardust Reverie\""],
	"SC083": ["083 - Magic Sign \"Stardust Reverie\""],
	"SC084": ["084 - Black Magic \"Event Horizon\""],
	"SC085": ["085 - Black Magic \"Event Horizon\""],
	"SC086": ["086 - Love Sign \"Non-Directional Laser\""],
	"SC087": ["087 - Love Sign \"Non-Directional Laser\""],
	"SC088": ["088 - Love Storm \"Starlight Typhoon\""],
	"SC089": ["089 - Love Storm \"Starlight Typhoon\""],
	"SC090": ["090 - Love Sign \"Master Spark\""],
	"SC091": ["091 - Love Sign \"Master Spark\""],
	"SC092": ["092 - Loving Heart \"Double Spark\""],
	"SC093": ["093 - Loving Heart \"Double Spark\""],
	"SC094": ["094 - Light Sign \"Earthlight Ray\""],
	"SC095": ["095 - Light Sign \"Earthlight Ray\""],
	"SC096": ["096 - Light Blast \"Shoot the Moon\""],
	"SC097": ["097 - Light Blast \"Shoot the Moon\""],
	"SC098": ["098 - Magicannon \"Final Spark\""],
	"SC099": ["099 - Magicannon \"Final Spark\""],
	"SC100": ["100 - Magicannon \"Final Master Spark\""],
	"SC101": ["101 - Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\""],
	"SC102": ["102 - Wave Sign \"Red-Eyed Hypnosis (Mind Shaker)\""],
	"SC103": ["103 - Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\""],
	"SC104": ["104 - Illusion Wave \"Red-Eyed Hypnosis (Mind Blowing)\""],
	"SC105": ["105 - Lunatic Sign \"Hallucination Tuning (Visionary Tuning)\""],
	"SC106": ["106 - Lunatic Sign \"Hallucination Tuning (Visionary Tuning)\""],
	"SC107": ["107 - Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\""],
	"SC108": ["108 - Lunatic Gaze \"Lunatic Stare Tuning (Illusion Seeker)\""],
	"SC109": ["109 - Loafing Sign \"Life & Spirit Stopping (Idling Wave)\""],
	"SC110": ["110 - Loafing Sign \"Life & Spirit Stopping (Idling Wave)\""],
	"SC111": ["111 - Indolence \"Life & Spirit Stopping (Mind Stopper)\""],
	"SC112": ["112 - Indolence \"Life & Spirit Stopping (Mind Stopper)\""],
	"SC113": ["113 - Spread Sign \"Moon of Truth (Invisible Full Moon)\""],
	"SC114": ["114 - Spread Sign \"Moon of Truth (Invisible Full Moon)\""],
	"SC115": ["115 - Spread Sign \"Moon of Truth (Invisible Full Moon)\""],
	"SC116": ["116 - Spread Sign \"Moon of Truth (Invisible Full Moon)\""],
	"SC117": ["117 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""],
	"SC118": ["118 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""],
	"SC119": ["119 - Lunar Eyes \"Lunar Rabbit's Remote Mesmerism (Tele-Mesmerism)\""],
	"SC120": ["120 - Spacesphere \"Earth in a Pot\""],
	"SC121": ["121 - Spacesphere \"Earth in a Pot\""],
	"SC122": ["122 - Spacesphere \"Earth in a Pot\""],
	"SC123": ["123 - Spacesphere \"Earth in a Pot\""],
	"SC124": ["124 - Awakened God \"Memories of the Age of the Gods\""],
	"SC125": ["125 - Awakened God \"Memories of the Age of the Gods\""],
	"SC126": ["126 - God Sign \"Genealogy of the Celestials\""],
	"SC127": ["127 - God Sign \"Genealogy of the Celestials\""],
	"SC128": ["128 - Revival \"Seimei Yugi -Life Game-\""],
	"SC129": ["129 - Revival \"Seimei Yugi -Life Game-\""],
	"SC130": ["130 - Resurrection \"Rising Game\""],
	"SC131": ["131 - Resurrection \"Rising Game\""],
	"SC132": ["132 - Leading God \"Omoikane's Device\""],
	"SC133": ["133 - Leading God \"Omoikane's Device\""],
	"SC134": ["134 - Mind of God \"Omoikane's Brain\""],
	"SC135": ["135 - Mind of God \"Omoikane's Brain\""],
	"SC136": ["136 - Curse of the Heavens \"Apollo 13\""],
	"SC137": ["137 - Curse of the Heavens \"Apollo 13\""],
	"SC138": ["138 - Curse of the Heavens \"Apollo 13\""],
	"SC139": ["139 - Curse of the Heavens \"Apollo 13\""],
	"SC140": ["140 - Esoterica \"Astronomical Cover-Up\""],
	"SC141": ["141 - Esoterica \"Astronomical Cover-Up\""],
	"SC142": ["142 - Esoterica \"Astronomical Cover-Up\""],
	"SC143": ["143 - Esoterica \"Astronomical Cover-Up\""],
	"SC144": ["144 - Forbidden Elixir \"Hourai Elixir\""],
	"SC145": ["145 - Forbidden Elixir \"Hourai Elixir\""],
	"SC146": ["146 - Forbidden Elixir \"Hourai Elixir\""],
	"SC147": ["147 - Forbidden Elixir \"Hourai Elixir\""],
	"SC148": ["148 - Medicine Sign \"Galaxy in a Pot\""],
	"SC149": ["149 - Medicine Sign \"Galaxy in a Pot\""],
	"SC150": ["150 - Medicine Sign \"Galaxy in a Pot\""],
	"SC151": ["151 - Medicine Sign \"Galaxy in a Pot\""],
	"SC152": ["152 - Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\""],
	"SC153": ["153 - Impossible Request \"Dragon's Neck's Jewel -Five-Colored Shots-\""],
	"SC154": ["154 - Divine Treasure \"Brilliant Dragon Bullet\""],
	"SC155": ["155 - Divine Treasure \"Brilliant Dragon Bullet\""],
	"SC156": ["156 - Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\""],
	"SC157": ["157 - Impossible Request \"Buddha's Stone Bowl -Indomitable Will-\""],
	"SC158": ["158 - Divine Treasure \"Buddhist Diamond\""],
	"SC159": ["159 - Divine Treasure \"Buddhist Diamond\""],
	"SC160": ["160 - Impossible Request \"Robe of Fire Rat -Patient Mind-\""],
	"SC161": ["161 - Impossible Request \"Robe of Fire Rat -Patient Mind-\""],
	"SC162": ["162 - Divine Treasure \"Salamander Shield\""],
	"SC163": ["163 - Divine Treasure \"Salamander Shield\""],
	"SC164": ["164 - Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\""],
	"SC165": ["165 - Impossible Request \"Swallow's Cowrie Shell -Everlasting Life-\""],
	"SC166": ["166 - Divine Treasure \"Life Spring Infinity\""],
	"SC167": ["167 - Divine Treasure \"Life Spring Infinity\""],
	"SC168": ["168 - Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\""],
	"SC169": ["169 - Impossible Request \"Bullet Branch of Hourai -Rainbow Danmaku-\""],
	"SC170": ["170 - Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\""],
	"SC171": ["171 - Divine Treasure \"Jeweled Branch of Hourai -Dreamlike Paradise-\""],
	"SC172": ["172 - End of Imperishable Night -New Moon-"],
	"SC173": ["173 - End of Imperishable Night -Crescent Moon-"],
	"SC174": ["174 - End of Imperishable Night -1st Quarter's Moon-"],
	"SC175": ["175 - End of Imperishable Night -Matsuyoi-"],
	"SC176": ["176 - End of Imperishable Night -11 o'Clock-"],
	"SC177": ["177 - End of Imperishable Night -Half of Midnight-"],
	"SC178": ["178 - End of Imperishable Night -Midnight-"],
	"SC179": ["179 - End of Imperishable Night -Half Past Midnight-"],
	"SC180": ["180 - End of Imperishable Night -1 o'Clock-"],
	"SC181": ["181 - End of Imperishable Night -Half Past 1-"],
	"SC182": ["182 - End of Imperishable Night -Dead of Night-"],
	"SC183": ["183 - End of Imperishable Night -Half Past 2-"],
	"SC184": ["184 - End of Imperishable Night -3 o'Clock-"],
	"SC185": ["185 - End of Imperishable Night -Half Past 3-"],
	"SC186": ["186 - End of Imperishable Night -4 o'Clock-"],
	"SC187": ["187 - End of Imperishable Night -Half Past 4-"],
	"SC188": ["188 - End of Imperishable Night -Morning Mist-"],
	"SC189": ["189 - End of Imperishable Night -Dawn-"],
	"SC190": ["190 - End of Imperishable Night -Morning Star-"],
	"SC191": ["191 - End of Imperishable Night -Rising World-"],
	"SC192": ["192 - Past \"Old History of an Untrodden Land -Old History-\""],
	"SC193": ["193 - Reincarnation \"Ichijou Returning Bridge\""],
	"SC194": ["194 - Future \"New History of Fantasy -Next History-\""],
	"SC195": ["195 - Statute of Limitations \"Curse of Tsuki no Iwakasa\""],
	"SC196": ["196 - Undying \"Fire Bird -Feng Wing Ascension-\""],
	"SC197": ["197 - Fujiwara \"Wounds of Metsuzai Temple\""],
	"SC198": ["198 - Undying \"Xu Fu's Dimension\""],
	"SC199": ["199 - Expiation \"Honest Man's Death\""],
	"SC200": ["200 - Hollow Being \"Wu\""],
	"SC201": ["201 - Inextinguishable \"Phoenix's Tail\""],
	"SC202": ["202 - Hourai \"South Wind, Clear Sky -Fujiyama Volcano-\""],
	"SC203": ["203 - \"Possessed by Phoenix\""],
	"SC204": ["204 - \"Hourai Doll\""],
	"SC205": ["205 - \"Imperishable Shooting\""],
	"SC206": ["206 - \"Unseasonal Butterfly Storm\""],
	"SC207": ["207 - \"Blind Nightbird\""],
	"SC208": ["208 - \"Emperor of the Land of the Rising Sun\""],
	"SC209": ["209 - \"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\""],
	"SC210": ["210 - \"Heaven Spider's Butterfly-Capturing Web\""],
	"SC211": ["211 - \"Hourai's Sea of Trees\""],
	"SC212": ["212 - \"Phoenix Rebirth\""],
	"SC213": ["213 - \"Ancient Duper\""],
	"SC214": ["214 - \"Total Purification\""],
	"SC215": ["215 - \"Fantasy Nature\""],
	"SC216": ["216 - \"Blazing Star\""],
	"SC217": ["217 - \"Deflation World\""],
	"SC218": ["218 - \"Matsuyoi-Reflecting Satellite Slash\""],
	"SC219": ["219 - \"The Phantom of the Grand Guignol\""],
	"SC220": ["220 - \"Scarlet Destiny\""],
	"SC221": ["221 - \"Saigyouji Parinirvana\""],
	"SC222": ["222 - \"Profound Danmaku Barrier -Phantasm, Foam, and Shadow-\""]
}